id = "flow-icons"
name = "Flow Icons"
description = "Beautiful file icons for Zed"
version = "1.0.0"
schema_version = 1
authors = ["thang-nm", "alxrodav"]
repository = "https://github.com/alxrodav/flow-icons-zed"
